export const SET_TODOS = 'SET_TODOS'
export const ADD_TODO = 'ADD_TODO'
export const SET_FILTER = 'SET_FILTER'
export const REMOVE_TODO = 'REMOVE_TODO'
export const EDIT_TODO = 'EDIT_TODO'
export const TOGGLE_TODO_STATE = 'TOGGLE_TODO_STATE'
export const SET_ERROR = 'SET_ERROR'